root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 186, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 'AssemblyModel' object has no attribute 'subassembly_name'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 210, in post_assembly
    new_assembly = AnyNode(id=assembly.subassembly_name)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AssemblyModel' object has no attribute 'subassembly_name'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 'AssemblyModel' object has no attribute 'subassembly_name'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 210, in post_assembly
    new_assembly = AnyNode(id=assembly.subassembly_name)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AssemblyModel' object has no attribute 'subassembly_name'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 292, in get_assembly_first_level_children
    assembly_children = gAssemblies[assembly_name].children
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'test_assembly3'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 306, in get_assembly_children
    assembly_children = gAssemblies[assembly_name].descendants
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'test_assembly3'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 320, in get_assembly_leaves
    assembly_children = gAssemblies[assembly_name].leaves
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'test_assembly3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 186, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 'AssemblyModel' object has no attribute 'subassembly_name'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 219, in post_assembly
    gAssembly_parts[assembly.subassembly_name] = new_assembly
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AssemblyModel' object has no attribute 'subassembly_name'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 'AssemblyModel' object has no attribute 'subassembly_name'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 219, in post_assembly
    gAssembly_parts[assembly.subassembly_name] = new_assembly
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AssemblyModel' object has no attribute 'subassembly_name'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 292, in get_assembly_first_level_children
    assembly_children = gAssemblies[assembly_name].children
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'test_assembly3'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 306, in get_assembly_children
    assembly_children = gAssemblies[assembly_name].descendants
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'test_assembly3'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 320, in get_assembly_leaves
    assembly_children = gAssemblies[assembly_name].leaves
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'test_assembly3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 186, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 182, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 158, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 182, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 158, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - name 'assembly' is not defined
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 238, in detach_part_assembly
    if not assembly.part_names or not gParts:
           ^^^^^^^^
NameError: name 'assembly' is not defined
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 182, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 158, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - name 'assembly' is not defined
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 238, in detach_part_assembly
    if not assembly.part_names or not gParts:
           ^^^^^^^^
NameError: name 'assembly' is not defined
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 182, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 158, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 245, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 241, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 182, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 158, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 245, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 241, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 182, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 158, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 245, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 241, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 183, in post_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 244, in detach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 272, in attach_part_assembly
    raise HTTPException(status_code=403, detail="No parts created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 222, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 281, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 275, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 223, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 303, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 323, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 343, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 281, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 275, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 223, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 303, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 323, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 343, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 256, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 250, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 284, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 278, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 224, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 306, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 326, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 346, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 189, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 257, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 251, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 285, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 279, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 225, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 307, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 327, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 347, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 119, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 190, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 166, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 255, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 249, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 277, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_assembly2'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 225, in post_assembly
    gAssemblies[subassembly_name].parent = new_assembly
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'test_assembly2'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 305, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 325, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 345, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 449, in post_project
    gParts, gAssemblies, gAssembly_parts = {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 449, in post_project
    gParts, gAssemblies, gAssembly_parts = {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 449, in post_project
    gParts, gAssemblies, gAssembly_parts = {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 449, in post_project
    gParts, gAssemblies, gAssembly_parts = {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 449, in post_project
    gParts, gAssemblies, gAssembly_parts = {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 193, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 281, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 275, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 449, in post_project
    gParts, gAssemblies, gAssembly_parts = {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 281, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 275, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 281, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 275, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 193, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 193, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 281, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 275, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 188, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 193, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 193, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 253, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 247, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 281, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 275, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 192, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 192, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 192, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 192, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 192, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 302, in get_assembly_first_level_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 322, in get_assembly_children
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 342, in get_assembly_leaves
    raise HTTPException(status_code=403, detail="Assembly name not created")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 'test_part3'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 135, in get_part_ancestors
    part_ancestors = gParts[part_name].ancestors
                     ~~~~~~^^^^^^^^^^^
KeyError: 'test_part3'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 192, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 103, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 192, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 117, in delete_part
    raise HTTPException(status_code=403, detail="Part not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 187, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 163, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 252, in detach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 246, in detach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 280, in attach_part_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 274, in attach_part_assembly
    raise HTTPException(status_code=403, detail="Assembly name doesn't exist")
fastapi.exceptions.HTTPException
